version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - muleyuck
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: / # Location of go.mod
    assignees:
      - muleyuck
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 2
    groups:
      tui-dependencies:
        patterns:
          - "github.com/gdamore/tcell*"
          - "github.com/rivo/tview*"
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
