name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  ci:
    permissions:
      contents: read
    uses: muleyuck/github-actions/.github/workflows/ci-go.yml@v1
