name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    name: Lint Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod tidy
      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.2
        with:
          version: v2.11.1
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
